[package]
name = "winhash"
version = "0.1.0"
edition = "2021"
authors = ["Eitan Schwartz"]

[dependencies]
sha2 = "0.10.8"

[[bin]]
name = "winhash"
path = "src/main.rs"

[[test]]
name="hash_test"
path="src/tests/test_hash.rs"